### ISSUE TITLE
Crash on Amazon Kindle Fire (modified Android 2.3)

### ISSUE THREAD

**Issue by bvibber** [yuvipanda/WPSignpost#31]
Different crash than I get on the Galaxy Tab...

App starts to open, appears to show actionbar, spinner runs, then it crashes with this backtrace:

D/AndroidRuntime(  614): Shutting down VM
W/dalvikvm(  614): threadid=1: thread exiting with uncaught exception (group=0x40015560)
E/AndroidRuntime(  614): FATAL EXCEPTION: main
E/AndroidRuntime(  614): java.lang.NoSuchMethodError: in.yuvi.wpsignpost.PostsActivity.getActionBar
E/AndroidRuntime(  614):    at in.yuvi.wpsignpost.PostsActivity.showIssue(PostsActivity.java:116)
E/AndroidRuntime(  614):    at in.yuvi.wpsignpost.PostsActivity.access$2(PostsActivity.java:102)
E/AndroidRuntime(  614):    at in.yuvi.wpsignpost.PostsActivity$FetchIssuesTask.onPostExecute(PostsActivity.java:77)
E/AndroidRuntime(  614):    at in.yuvi.wpsignpost.PostsActivity$FetchIssuesTask.onPostExecute(PostsActivity.java:1)
E/AndroidRuntime(  614):    at android.os.AsyncTask.finish(AsyncTask.java:417)
E/AndroidRuntime(  614):    at android.os.AsyncTask.access$300(AsyncTask.java:127)
E/AndroidRuntime(  614):    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:429)
E/AndroidRuntime(  614):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(  614):    at android.os.Looper.loop(Looper.java:130)
E/AndroidRuntime(  614):    at android.app.ActivityThread.main(ActivityThread.java:3683)
E/AndroidRuntime(  614):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(  614):    at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime(  614):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:850)
E/AndroidRuntime(  614):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
E/AndroidRuntime(  614):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager( 1398):   Force finishing activity in.yuvi.wpsignpost/.PostsActivity

**Comment by yuvipanda** [comment]
Possibly fixed in the same commit that fixed #46. Can you test and confirm?

**Comment by bvibber** [comment]
Kindle's at home, I won't be able to test until I get back from vacation next week.

**Comment by bvibber** [comment]
Current master build still crashes, but on a different thing:

java.lang.RuntimeException: Unable to create application in.yuvi.wpsignpost.SignpostApp: java.lang.UnsupportedOperationException: Device does not have package com.google.android.gsf
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3275)
    at android.app.ActivityThread.access$2200(ActivityThread.java:117)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:969)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3683)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:850)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.UnsupportedOperationException: Device does not have package com.google.android.gsf
    at com.google.android.gcm.GCMRegistrar.checkDevice(GCMRegistrar.java:98)
    at in.yuvi.wpsignpost.SignpostApp.onCreate(SignpostApp.java:23)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3272)

**Comment by yuvipanda** [comment]
Indeed, that's the crash for Push notifications.

On Wed, Sep 5, 2012 at 11:47 PM, Brion Vibber notifications@github.comwrote:

> Current master build still crashes, but on a different thing:
> 
> java.lang.RuntimeException: Unable to create application
> in.yuvi.wpsignpost.SignpostApp: java.lang.UnsupportedOperationException:
> Device does not have package com.google.android.gsf
> at
> android.app.ActivityThread.handleBindApplication(ActivityThread.java:3275)
> at android.app.ActivityThread.access$2200(ActivityThread.java:117)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:969)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loop(Looper.java:130)
> at android.app.ActivityThread.main(ActivityThread.java:3683)
> at java.lang.reflect.Method.invokeNative(Native Method)
> at java.lang.reflect.Method.invoke(Method.java:507)
> at
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:850)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
> at dalvik.system.NativeStart.main(Native Method)
> Caused by: java.lang.UnsupportedOperationException: Device does not have
> package com.google.android.gsf
> at com.google.android.gcm.GCMRegistrar.checkDevice(GCMRegistrar.java:98)
> at in.yuvi.wpsignpost.SignpostApp.onCreate(SignpostApp.java:23)
> at
> android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
> at
> android.app.ActivityThread.handleBindApplication(ActivityThread.java:3272)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/yuvipanda/WPSignpost/issues/31#issuecomment-8308337.

## 

Yuvi Panda T
http://yuvi.in/blog

**Comment by yuvipanda** [comment]
This was fixed in 19b76f0ef848d893496f975ae5031b732d584c94 (and saper tested it on his non-googled phone)
